name: Windows

on:
  push:
    branches: [ "main", "windows" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: windows-msvc
            os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.32"
          distribution: strawberry

      - name: Build
        run: |
          cargo install cargo-packager
          cargo packager --release

      - name: Prepare files
        shell: bash
        run: |
          ls -al target
          ls -al target/*
          ls -al target/*/*
          binary_name="mlm"
          version="${GITHUB_REF#refs/tags/v}"
          version="${version#refs/heads/}"
          app="$binary_name-$version.exe"
          installer="$binary_name-$version-x64-setup.exe"
          echo "APP=$app" >> $GITHUB_ENV
          echo "INSTALLER=$installer" >> $GITHUB_ENV
          mv "target/release/${binary_name}_"*"-setup.exe" "$installer"
          mv "target/release/$binary_name.exe" "$app"

      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP }} 
          path: ${{ env.APP }} 

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.INSTALLER }} 
          path: ${{ env.INSTALLER }} 

      - name: Create release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.INSTALLER }}
