name: Windows

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - build: windows-msvc
            os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.32"
          distribution: strawberry

      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Prepare files
        shell: bash
        run: |
          binary_name="mlm"
          version="${GITHUB_REF#refs/tags/}"
          version="${version#refs/heads/}"
          asset="$binary_name-$version-${{ matrix.target }}.exe"
          echo "ASSET=$asset" >> $GITHUB_ENV
          mv "target/${{ matrix.target }}/release/$binary_name.exe" "$asset"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ASSET }} 
          path: ${{ env.ASSET }} 

      - name: Create release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ASSET }}
